// <auto-generated />
using System;
using DriveAnheu.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DriveAnheu.Infrastructure.Migrations
{
    [DbContext(typeof(DriveAnheuContext))]
    [Migration("20231119152343_AddHistoricoExpiracao")]
    partial class AddHistoricoExpiracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DriveAnheu.Domain.Entities.HistoricoExpiracao", b =>
                {
                    b.Property<int>("HistoricoExpiracaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.HasKey("HistoricoExpiracaoId");

                    b.HasIndex("Data");

                    b.ToTable("HistoricosExpiracoes");
                });

            modelBuilder.Entity("DriveAnheu.Domain.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("GuidPastaPai")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("Guid");

                    b.HasIndex("GuidPastaPai");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("DriveAnheu.Domain.Entities.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Endpoint")
                        .HasColumnType("longtext");

                    b.Property<string>("Parametros")
                        .HasColumnType("longtext");

                    b.Property<int>("StatusResposta")
                        .HasColumnType("int");

                    b.Property<string>("TipoRequisicao")
                        .HasColumnType("longtext");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("DriveAnheu.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Guid");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DriveAnheu.Domain.Entities.Item", b =>
                {
                    b.HasOne("DriveAnheu.Domain.Entities.Usuario", "Usuarios")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("DriveAnheu.Domain.Entities.Log", b =>
                {
                    b.HasOne("DriveAnheu.Domain.Entities.Usuario", "Usuarios")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
